name: Build and Upload Artifact
on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build project
        run: ./gradlew clean && ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: HasiBot
          path: build/libs/
